### ISSUE TITLE
Incomplete template

### ISSUE THREAD

**Issue by bpelikan** [MicrosoftDocs/mslearn-n-tier-architecture#17]
Current template in [Tour the N-tier architecture style for your application -> Exercise - Deploy an N-tier architecture](https://docs.microsoft.com/en-us/learn/modules/n-tier-architecture/3-deploy-n-tier-architecture) is creating only network related services like `Network security group` and `Virtual network`, but not a complete application.

![image](https://user-images.githubusercontent.com/24376947/67152049-c80da400-f2cf-11e9-83da-5e487663abb6.png)

**Comment by jboeshart** [comment]
Fixed in #16, thanks for your contribution @bpelikan!
